### PR TITLE
adventure

### PR DESCRIPTION
**Pull request by ohheuck**

### CODE REVIEW

**Comment by LazyRen** [comment]
You should NOT create pull request for the posts you've made nor personalized settings.
Just keep your personal stuffs to your own forked repo plz.

**Comment by qwtel** [comment]
Most likely an accident. Happens every once in a while 🙂

**Comment by ohheuck** [comment]
I am a student who is not good at coding GitHub for the first time
yesterday. I think the current situation is due to the full request. I
don't know. I'll delete them all. I'm so sorry.
ᐧ

2020년 12월 18일 (금) 오전 12:35, Florian Klampfer <notifications@github.com>님이
작성:

**Comment by ohheuck** [comment]
I'm so sorry, but how can I delete the full request I posted? I want to delete it, but I can only see the edit button. If you can delete it, please delete it...

**Comment by qwtel** [comment]
Don't worry, nothing bad happend 🙂 You'll get used to it.

**Comment by qwtel** [comment]
Unfortunately PRs can't deleted from GitHub. If this contains sensitive information, reach out to GitHub Support to have it removed.

**Comment by ohheuck** [comment]
Thank you so much! There's no sensitive part because I erased all the
contents(only contents). Is there any disadvantage to you because of my
uninstalled full request?
ᐧ

2020년 12월 18일 (금) 오전 12:56, Florian Klampfer <notifications@github.com>님이
작성:

**Comment by ohheuck** [comment]
Thank you so much! There's no sensitive part because I erased all the
contents(only contents). Is there any disadvantage to you because of my
undeleted full request?
ᐧ

2020년 12월 18일 (금) 오전 12:59, ‍권오혁[학생](전자정보대학 전자공학과) <kwonoh3842@khu.ac.kr>님이
작성:

**Comment by qwtel** [comment]
No disadvantage to me . 
Thanks for trying out Hydejack 🙃

**Comment by ohheuck** [comment]
Yes!!😁😁😁
ᐧ

2020년 12월 18일 (금) 오전 1:08, Florian Klampfer <notifications@github.com>님이 작성:

**Pull request closed without merging**
